apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka.fullname" . }}-init-scripts
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
data:
  init.sh: |
{{ .Files.Get "init-scripts/init.sh" | indent 4 }}
